### ISSUE TITLE
make book loading asynchronous

### ISSUE THREAD

**Issue by alinelena** [monich/harbour-books#10]
At the moment when one loads a book needs to wait till all pages are somehow formatted... 
make this process asynchronous. Once first page needs to be displayed is ready display it and then continue in background with the rest of loading.

Alin

**Comment by qeef** [comment]
:+1: it shouldn't be so hard, @monich ?

**Comment by monich** [comment]
Of course it's software, where everything is possible. But no, it's not trivial. We don't know the total number of pages until we have loaded the entire book. And the slider/pager at the bottom will be broken until we know the total number of pages. And we can't start from the arbitrary page, we have to start from the very beginning. So if you are opening the book at the page closer to the end, interrupting the formatting to show the current page won't really help - you would still have to parse pretty much the whole thing before you see the current page.

I'm leaning towards saving the formatting information to a file on the first use (like covers are cached) and then loading it from there. That would make loading much faster and it's conceptually easier than interrupting the formatting/dealing with the broken pager/continuing after displaying the current page and then somehow concatenating two pieces of the formatting information together.

**Comment by monich** [comment]
In 1.0.25 (when it's released) the page marks will be cached. That is, the first time it will be slow but from that point on the book will be loaded very quickly, almost instantly. That, I guess resolves this issue.
