### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by monich** [monich/harbour-books#15]
It would be nice to be able to select and copy the text to the clipboard.

**Comment by paolomi** [comment]
yes! For example, if you read a book written in another language, it's very useful to select the word you don't know and paste it into the translation program

**Comment by monich** [comment]
Copy to clipboard has been implemented in version 1.0.23 (long press on a text to activate the selection mode). Version 1.0.24 will add haptic feedback to make it easier to discover and use this feature.
