### ISSUE TITLE
[Tablet] update fails

### ISSUE THREAD

**Issue by Nokius** [monich/harbour-books#17]
On my Jolla tablet I get since month the notification that there is an update to version 1.0.10.
When I trace journalctl during the update I see this message 

`Apr 19 22:14:01 Jolla [1547]: [D] Package::InstallTransactionPkgKit::update:198 - void Package::InstallTransactionPkgKit::update(const QString&) "harbour-books;1.0.10-93.1;i486;store" 
Apr 19 22:14:01 Jolla estart[1127]: [D] DeveloperModeSettingsWorker::onPackageProgressChanged:188 - onPackageProgressChanged: "harbour-books" 49 
Apr 19 22:14:01 Jolla estart[1127]: [D] DeveloperModeSettingsWorker::onPackageProgressChanged:188 - onPackageProgressChanged: "harbour-books" 49 
Apr 19 22:14:01 Jolla [1547]: [D] Package::InstallTransactionPkgKit::slotTransactionError:377 - void Package::InstallTransactionPkgKit::slotTransactionError(PackageKit::Transaction::Error, const QString&) 13 "There is ....70.1.jolla.i486" 
Apr 19 22:14:01 Jolla [1547]: [D] Package::InstallTransactionPkgKit::giveUpOrRetry:222 - void Package::InstallTransactionPkgKit::giveUpOrRetry(const QString&) "There is no update candidate for harbour-books-1.0.6-10.70.1.jolla.i486" 
Apr 19 22:14:01 Jolla estart[1127]: [D] DeveloperModeSettingsWorker::onPackageProgressChanged:188 - onPackageProgressChanged: "harbour-books" 49 
Apr 19 22:14:01 Jolla [1547]: [D] Package::InstallTransactionPkgKit::giveUpOrRetry:259 - giving up 
Apr 19 22:14:01 Jolla estart[1127]: [D] DeveloperModeSettingsWorker::onPackageProgressChanged:188 - onPackageProgressChanged: "harbour-books" 100 
Apr 19 22:14:01 Jolla lipstick[690]: [D] displayNotification:311 - Warning: Notification is non-standard, it has both preview summary and preview body but no actions. Remove the preview body or add an action: Store x-j...d not update Books
Apr 19 22:14:02 Jolla [1547]: [D] Package::RepositoryTransactionPkgKit::slotWrappedTransactionFailure:306 - Wrapped transaction failed: "There is no update candidate for harbour-books-1.0.6-10.70.1.jolla.i486" 
Apr 19 22:14:02 Jolla [1547]: [D] Package::InstallTransactionPkgKit::~InstallTransactionPkgKit:43 - deleting InstallTransactionPkgKit `

current version is 
`rpm -qa | grep books  
harbour-books-1.0.6-10.70.1.jolla.i486`

Not sure if the i486 rpm is missing or it's an issue with the store

**Comment by Nokius** [comment]
uninstall and a reinstall is atm the workaround :s

**Comment by monich** [comment]
Damn, mer OBS default setup has changed and that changed rpm vendor without me knowing anything about that.

**Comment by monich** [comment]
Particularly, it's the Vendor attribute that's changed

**Comment by monich** [comment]
Nothing to be done about it I guess. I'll be more careful from now on. Closing.

On the other hand, when Jolla QA accepts update to the store, they are supposed to check the rpm vendor to make sure that it matches the last know value but somehow it escaped them as well. Oh well...

**Comment by Nokius** [comment]
@monich did reported this 'bug' to Jolla QA?

**Comment by monich** [comment]
Yes, personally.
