### ISSUE TITLE
footnotes support

### ISSUE THREAD

**Issue by paolomi** [monich/harbour-books#23]
Add a smart way in order to read footnotes: touch the footnote, read the citation, and go back to the text. Many thanks

**Comment by monich** [comment]
`<aside>` style footnotes with `epub:type="footnote"` are supported since version 1.0.18 (you need to long-tap on those). Do you have an example of a book where footnotes don't show up?

**Comment by paolomi** [comment]
@monich 
OMG, my touch was too short! It works! many thanks! I close the bug. Sorry for wasting your time.
