### ISSUE TITLE
Sd-card directory changed in 2.2.x

### ISSUE THREAD

**Issue by hsjpekka** [monich/harbour-books#46]
Books doesn't find books in sd-card. The directory is now /run/media/nemo/[sdcardNumber]

**Comment by monich** [comment]
This problem is supposed to be fixed in the latest release (1.0.34), particularly by commits fbadaf14 and then 7b38eca3. Which version are you running?

**Comment by hsjpekka** [comment]
Sorry, a user error. When I opened Books (1.0.34), it showed in big letters 'You don't have any books.' But it was the contents of the internal memory.
I have always had all books in sd-card, so I didn't remember that there is one page for internal memory and another for sd-card.
