### ISSUE TITLE
Allow locking/preventing specific rotations

### ISSUE THREAD

**Issue by Mikaela** [monich/harbour-books#5]
I prefer to read the books in normal mode (text is correct way when the led points to me) and when I turn a little books think that I want to be in horizontal mode, which I dislike. It would be nice if there was option for locking specific rotations or only using some of the 4 possible rotations.

**Comment by monich** [comment]
In case if you didn't know, you can prevent Sailfish UI from changing the orientation by holding your finger on the screen when you are turning the device. Isn't that sufficient?

**Comment by Mikaela** [comment]
I don't ever remember to do it and that makes me turn the phone around again and holding finger and then turning again which is a little difficult.

**Comment by monich** [comment]
Implemented (d8964ee8)

**Comment by monich** [comment]
This feature is available in version 1.0.13
