### ISSUE TITLE
Polish characters issue

### ISSUE THREAD

**Issue by N-Madsen** [monich/harbour-books#50]
Hello, I encountered a problem with polish special characters such as ą ś ć ż ź etc, its displayed as a something like 1/3 1/4 and some other characters similar to "A". 

example of book affected with problem: 
https://wolnelektury.pl/media/book/mobi/homer-odyseja.mobi

regards,

**Comment by monich** [comment]
Commit ffb9e88 should fix it. I hope it won't break anything else :)

**Comment by monich** [comment]
The fix is included in version 1.0.38. Submitted update to both OpenRepos and Jolla Store. Thanks for the report!
