### ISSUE TITLE
Permacrashing because of an epub

### ISSUE THREAD

**Issue by glacambre** [monich/harbour-books#53]
Hi. Thank you for working on Books, I am very happy to be able to use it to read epubs on my phone.

I tried to load an epub file (you can download it [here](https://gallica.bnf.fr/ark:/12148/bpt6k54008103/f6.image.texteImage): click on the "down" arrow on the left, select "epub", full document, tick the box and click "download"). Importing it in the library was fine but actually attempting to read it made Books crash. I tried to reboot my phone (Xperia X with Sailfish) and reinstall Books but nothing worked, and now I can't even start Books anymore.

I can provide logs if you want - just tell me how to get them.

Again, thank you for all the time you spent working on Books, I'm very grateful!

**Comment by monich** [comment]
Nice choice of reading :) Even though I don't know French, I have recognized the book.

Yep, I've been able to reproduce the crash. Will fix it, thanks for the report!

**Comment by monich** [comment]
It's actually easy enough to fix the immediate cause of the crash but I need some time to think how to make this stuff work the way it's supposed to (this has to do with footnotes)...

**Comment by monich** [comment]
Since I haven't came up with anything better by now, build 1.0.39 should at least fix the crash. Let me know how it works for you.

**Comment by glacambre** [comment]
I can confirm that the latest Books version available on the Jolla store fixes this issue. Thanks! :)

**Comment by monich** [comment]
Great, I'm glad it helped. Cheers!
